### PR TITLE
Partially claim Lightning zap polls

### PR DESCRIPTION
**Pull request by toadlyBroodle**
Will update 'pending' to 'paid' after payment is received. Thanks.

### CODE REVIEW

**Comment by nvk** [comment]
What's the BTC address for the payment?

**Comment by nvk** [comment]
@stacksatsio please comment here with the payment address since this is your bounty.

**Comment by toadlyBroodle** [comment]
> What's the BTC address for the payment?

@stacksatsio sent payment to bc1qxa982cmy7x7zul7x0qtgp9sukvy7jaezhnjxmlk3n7r7npgjhj8qm2saj4

**Comment by nvk** [comment]
@stacksatsio please confirm.

**Comment by stacksatsio** [comment]
StackSatsIO confirming payment of 0.1 BTC for Lightning polls

**Comment by nvk** [comment]
Paid. Paid https://mempool.space/tx/c6c78ac37fa4f173390b4b7bb477e1a2c3be820ae960a7995c2218dfed86c3bc

**Comment by toadlyBroodle** [comment]
Awesome, thanks so much for supporting nostr devs!

**Pull request merged**
