### PR TITLE
remove some bounties, claim other

### PR DESCRIPTION
**Pull request by fiatjaf**
I must think of bounties of less and more strict scope, otherwise I'll go crazy.

### CODE REVIEW

**Comment by nvk** [comment]
Not sure if we should delete, maybe someone already started. If you really want to, we can delete. But would be better if we add a new status, call it `cancelled` or something along the lines and I will add logic to move them to the bottom.

**Comment by fiatjaf** [comment]
Ok, makes sense.

**Comment by nvk** [comment]
updated for you, let me know if this is what you like

**Comment by fiatjaf** [comment]
Looks good. Thank you very much.

**Pull request merged**
